server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_eats_dev?useSSL=false&serverTimezone=UTC
    username: daily_eats
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
